// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdErEqUAuAvPdq0kHHzqKSm6ZiaFSxG0',
    appId: '1:654504161698:web:e8302bb23f829a97a982fb',
    messagingSenderId: '654504161698',
    projectId: 'moonnlove-a78ca',
    authDomain: 'moonnlove-a78ca.firebaseapp.com',
    storageBucket: 'moonnlove-a78ca.firebasestorage.app',
    measurementId: 'G-QSBM6YQ786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNINZlibUf5jhpYZ8io_MyWfsVnFyXaq0',
    appId: '1:654504161698:android:6b902a5846117b32a982fb',
    messagingSenderId: '654504161698',
    projectId: 'moonnlove-a78ca',
    storageBucket: 'moonnlove-a78ca.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtnwg_hNLCJRQa2PTQYMIzVIDtcC_eDE',
    appId: '1:654504161698:ios:e172d9ecd1a329c8a982fb',
    messagingSenderId: '654504161698',
    projectId: 'moonnlove-a78ca',
    storageBucket: 'moonnlove-a78ca.firebasestorage.app',
    iosBundleId: 'com.example.moonnlove',
  );
}
